#ifndef SIMPLE_INTERPRETER_STATEMENTTYPE_H
#define SIMPLE_INTERPRETER_STATEMENTTYPE_H

enum StatementType {
    ASSIGNMENT,
    GOTO,
    INVALID,
    IF

};

#endif //SIMPLE_INTERPRETER_STATEMENTTYPE_H
